language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: HT+L7iAlp/i+5FbjkdfC2lEeM3rEL5Sm7SqTG2cL7xdnbr64AY9Hp6Tk+09CXiy+av6O6+hDupnrdscg8dDvdB4BQDrwVIJ30Xg3PnvjYeY0Y3WZc3zPEKGbD5CqVfjRXgFthoVEiolZ31pZOGAck+EyBrmJOoGHUH0UbXwAyLtOgmN4Vj1jQ4uYVumc09SikxRUpH/ZgdEQG0W4e2CpNN2LCkuikUu7NbCgpdMt6DnzFqpMUYfeNLHyCq7DASb32MO8eoy4Vml8gKmDAsAKvowEKuZK0ll2Sg9scmAokRQD1Wd9f34z5V2nmxy+8jick17VTSQezEzMcxKubUf3P11bsy7wS88Khgt8HzpHEMUmB0wEviHM9njswHwy1NxQXKl+1PIWmX6hnC/oCuxu7/IETidUX80V8hce9Z6ZRn2Bo84rAfcUUlraKd9nXA1jseFoW8FPfidg52Co3DanTEd4172XoVoxuUqYGJDzvHodRmIvPViAdvwrHZgeCDVC4da0A4YeQ1bzPSwZpNYT96WAfqmwMKkPgxocVFYaKHXm1uU0yidTVFVcc+SCFUKfiLM48QOxOOiXcyQirfAhKd44WdKJsNxn5YbIezlYc2PfO1ETw8DZIEN6dc8xpi/S0zwjoF7UnDyNGQIoIjRJoJm3/4NQT7j5gk69HzjJKKs=
  app: https://git.heroku.com/fast-thicket-95294.git
  on:
    repo: kelseybutler9/node-shopping-list-integration-tests
